services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: hassan1999/docker-spring-boot
    container_name: docker-spring-boot
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb