version: "3.7"

services:
  mysqldb:
   container_name: mysqldb
   image: mysql:5.7
   restart: unless-stopped
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tpachato
   ports:
    - 3306:3306    
   volumes:
      - db:/var/lib/mysql

  spring_app:
   image: hassan1999/docker-spring-boot
   container_name: docker-spring-boot
   ports:
    - 8089:8089
   environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
   restart: on-failure
   links:
      - mysqldb